# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  release
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.18.1]

    steps:
      - name: Checkout code
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
              npm i nexe
              npm i
              npm run build-win-x64
              npm run build-mac-x64
              npm run build-win-x86
              npm run build-mac-x86
                
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'bin/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
